apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ .Values.userID }}{{ .Values.nameSuffix }}
  namespace: showks
  labels:
    app: {{ .Chart.Name }}-{{ .Values.userID }}{{ .Values.nameSuffix }}
    class: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-{{ .Values.userID }}{{ .Values.nameSuffix }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-{{ .Values.userID }}{{ .Values.nameSuffix }}
        class: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-{{ .Values.userID }}{{ .Values.nameSuffix }}
          image: gcr.io/ipc-cloudnativedays/{{ .Chart.Name }}-{{ .Values.userID }}:{{ .Values.image.tag }}
          ports:
            - name: app-port
              containerPort: 8080
              protocol: TCP
